// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: endpoint_service.proto

package grpctunnel_demo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HubEvent int32

const (
	HubEvent_CLIENT_CONTROL_UNSPECIFIED HubEvent = 0
	HubEvent_CLIENT_CONTROL_SUBSCRIBE   HubEvent = 1
	HubEvent_CLIENT_CONTROL_UNSUBSCRIBE HubEvent = 2
)

// Enum value maps for HubEvent.
var (
	HubEvent_name = map[int32]string{
		0: "CLIENT_CONTROL_UNSPECIFIED",
		1: "CLIENT_CONTROL_SUBSCRIBE",
		2: "CLIENT_CONTROL_UNSUBSCRIBE",
	}
	HubEvent_value = map[string]int32{
		"CLIENT_CONTROL_UNSPECIFIED": 0,
		"CLIENT_CONTROL_SUBSCRIBE":   1,
		"CLIENT_CONTROL_UNSUBSCRIBE": 2,
	}
)

func (x HubEvent) Enum() *HubEvent {
	p := new(HubEvent)
	*p = x
	return p
}

func (x HubEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HubEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_endpoint_service_proto_enumTypes[0].Descriptor()
}

func (HubEvent) Type() protoreflect.EnumType {
	return &file_endpoint_service_proto_enumTypes[0]
}

func (x HubEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HubEvent.Descriptor instead.
func (HubEvent) EnumDescriptor() ([]byte, []int) {
	return file_endpoint_service_proto_rawDescGZIP(), []int{0}
}

type EndpointMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HubEvent  HubEvent `protobuf:"varint,1,opt,name=hub_event,json=hubEvent,proto3,enum=HubEvent" json:"hub_event,omitempty"`
	DataChunk []byte   `protobuf:"bytes,2,opt,name=data_chunk,json=dataChunk,proto3" json:"data_chunk,omitempty"`
}

func (x *EndpointMessage) Reset() {
	*x = EndpointMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndpointMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointMessage) ProtoMessage() {}

func (x *EndpointMessage) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointMessage.ProtoReflect.Descriptor instead.
func (*EndpointMessage) Descriptor() ([]byte, []int) {
	return file_endpoint_service_proto_rawDescGZIP(), []int{0}
}

func (x *EndpointMessage) GetHubEvent() HubEvent {
	if x != nil {
		return x.HubEvent
	}
	return HubEvent_CLIENT_CONTROL_UNSPECIFIED
}

func (x *EndpointMessage) GetDataChunk() []byte {
	if x != nil {
		return x.DataChunk
	}
	return nil
}

type HubMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HubEvent  HubEvent `protobuf:"varint,1,opt,name=hub_event,json=hubEvent,proto3,enum=HubEvent" json:"hub_event,omitempty"`
	DataChunk []byte   `protobuf:"bytes,2,opt,name=data_chunk,json=dataChunk,proto3" json:"data_chunk,omitempty"`
}

func (x *HubMessage) Reset() {
	*x = HubMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubMessage) ProtoMessage() {}

func (x *HubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubMessage.ProtoReflect.Descriptor instead.
func (*HubMessage) Descriptor() ([]byte, []int) {
	return file_endpoint_service_proto_rawDescGZIP(), []int{1}
}

func (x *HubMessage) GetHubEvent() HubEvent {
	if x != nil {
		return x.HubEvent
	}
	return HubEvent_CLIENT_CONTROL_UNSPECIFIED
}

func (x *HubMessage) GetDataChunk() []byte {
	if x != nil {
		return x.DataChunk
	}
	return nil
}

type TcpListenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TunnelId string `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Host     string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port     string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *TcpListenRequest) Reset() {
	*x = TcpListenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcpListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpListenRequest) ProtoMessage() {}

func (x *TcpListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpListenRequest.ProtoReflect.Descriptor instead.
func (*TcpListenRequest) Descriptor() ([]byte, []int) {
	return file_endpoint_service_proto_rawDescGZIP(), []int{2}
}

func (x *TcpListenRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TcpListenRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TcpListenRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

var File_endpoint_service_proto protoreflect.FileDescriptor

var file_endpoint_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x09, 0x68, 0x75, 0x62, 0x5f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x48, 0x75,
	0x62, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x68, 0x75, 0x62, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22,
	0x53, 0x0a, 0x0a, 0x48, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a,
	0x09, 0x68, 0x75, 0x62, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x09, 0x2e, 0x48, 0x75, 0x62, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x68, 0x75, 0x62,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x22, 0x57, 0x0a, 0x10, 0x54, 0x63, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x2a, 0x68, 0x0a,
	0x08, 0x48, 0x75, 0x62, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4c, 0x49,
	0x45, 0x4e, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4c, 0x49,
	0x45, 0x4e, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x5f, 0x53, 0x55, 0x42, 0x53,
	0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4c, 0x49, 0x45, 0x4e,
	0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x55, 0x42, 0x53,
	0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x02, 0x32, 0x56, 0x0a, 0x0a, 0x48, 0x75, 0x62, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x63, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x41, 0x6e, 0x64, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x12, 0x11, 0x2e, 0x54, 0x63, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x32,
	0x42, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x50, 0x69, 0x70, 0x65, 0x12, 0x0b,
	0x2e, 0x48, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x10, 0x2e, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x31, 0x30, 0x31, 0x30, 0x31, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_endpoint_service_proto_rawDescOnce sync.Once
	file_endpoint_service_proto_rawDescData = file_endpoint_service_proto_rawDesc
)

func file_endpoint_service_proto_rawDescGZIP() []byte {
	file_endpoint_service_proto_rawDescOnce.Do(func() {
		file_endpoint_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_endpoint_service_proto_rawDescData)
	})
	return file_endpoint_service_proto_rawDescData
}

var file_endpoint_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_endpoint_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_endpoint_service_proto_goTypes = []interface{}{
	(HubEvent)(0),            // 0: HubEvent
	(*EndpointMessage)(nil),  // 1: EndpointMessage
	(*HubMessage)(nil),       // 2: HubMessage
	(*TcpListenRequest)(nil), // 3: TcpListenRequest
	(*emptypb.Empty)(nil),    // 4: google.protobuf.Empty
}
var file_endpoint_service_proto_depIdxs = []int32{
	0, // 0: EndpointMessage.hub_event:type_name -> HubEvent
	0, // 1: HubMessage.hub_event:type_name -> HubEvent
	3, // 2: HubService.CreateTcpListenerAndBlock:input_type -> TcpListenRequest
	2, // 3: EndpointService.DataPipe:input_type -> HubMessage
	4, // 4: HubService.CreateTcpListenerAndBlock:output_type -> google.protobuf.Empty
	1, // 5: EndpointService.DataPipe:output_type -> EndpointMessage
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_endpoint_service_proto_init() }
func file_endpoint_service_proto_init() {
	if File_endpoint_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_endpoint_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndpointMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HubMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TcpListenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_endpoint_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_endpoint_service_proto_goTypes,
		DependencyIndexes: file_endpoint_service_proto_depIdxs,
		EnumInfos:         file_endpoint_service_proto_enumTypes,
		MessageInfos:      file_endpoint_service_proto_msgTypes,
	}.Build()
	File_endpoint_service_proto = out.File
	file_endpoint_service_proto_rawDesc = nil
	file_endpoint_service_proto_goTypes = nil
	file_endpoint_service_proto_depIdxs = nil
}
