// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: endpoint_service.proto

package grpctunnel_demo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataChunk []byte `protobuf:"bytes,2,opt,name=data_chunk,json=dataChunk,proto3" json:"data_chunk,omitempty"`
}

func (x *EndpointMessage) Reset() {
	*x = EndpointMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndpointMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointMessage) ProtoMessage() {}

func (x *EndpointMessage) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointMessage.ProtoReflect.Descriptor instead.
func (*EndpointMessage) Descriptor() ([]byte, []int) {
	return file_endpoint_service_proto_rawDescGZIP(), []int{0}
}

func (x *EndpointMessage) GetDataChunk() []byte {
	if x != nil {
		return x.DataChunk
	}
	return nil
}

type HubMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataChunk []byte `protobuf:"bytes,4,opt,name=data_chunk,json=dataChunk,proto3" json:"data_chunk,omitempty"`
}

func (x *HubMessage) Reset() {
	*x = HubMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubMessage) ProtoMessage() {}

func (x *HubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubMessage.ProtoReflect.Descriptor instead.
func (*HubMessage) Descriptor() ([]byte, []int) {
	return file_endpoint_service_proto_rawDescGZIP(), []int{1}
}

func (x *HubMessage) GetDataChunk() []byte {
	if x != nil {
		return x.DataChunk
	}
	return nil
}

var File_endpoint_service_proto protoreflect.FileDescriptor

var file_endpoint_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x2b, 0x0a, 0x0a, 0x48, 0x75,
	0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x61,
	0x74, 0x61, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x32, 0x42, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x50, 0x69, 0x70, 0x65, 0x12, 0x0b, 0x2e, 0x48, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x10, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x27, 0x5a, 0x25, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x6d, 0x61, 0x64, 0x31,
	0x30, 0x31, 0x30, 0x31, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2d,
	0x64, 0x65, 0x6d, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_endpoint_service_proto_rawDescOnce sync.Once
	file_endpoint_service_proto_rawDescData = file_endpoint_service_proto_rawDesc
)

func file_endpoint_service_proto_rawDescGZIP() []byte {
	file_endpoint_service_proto_rawDescOnce.Do(func() {
		file_endpoint_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_endpoint_service_proto_rawDescData)
	})
	return file_endpoint_service_proto_rawDescData
}

var file_endpoint_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpoint_service_proto_goTypes = []interface{}{
	(*EndpointMessage)(nil), // 0: EndpointMessage
	(*HubMessage)(nil),      // 1: HubMessage
}
var file_endpoint_service_proto_depIdxs = []int32{
	1, // 0: EndpointService.DataPipe:input_type -> HubMessage
	0, // 1: EndpointService.DataPipe:output_type -> EndpointMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_endpoint_service_proto_init() }
func file_endpoint_service_proto_init() {
	if File_endpoint_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_endpoint_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndpointMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HubMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_endpoint_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_endpoint_service_proto_goTypes,
		DependencyIndexes: file_endpoint_service_proto_depIdxs,
		MessageInfos:      file_endpoint_service_proto_msgTypes,
	}.Build()
	File_endpoint_service_proto = out.File
	file_endpoint_service_proto_rawDesc = nil
	file_endpoint_service_proto_goTypes = nil
	file_endpoint_service_proto_depIdxs = nil
}
